"""
Render the README hero for computational-optics-lab.

The SVG layout (assets/readme/source/hero-layout.svg) is the editable design
source. This script renders the published hero.png by drawing the typography
with Pillow + system fonts and pasting real simulation output (the figures
generated by three-propagation-models-clean-version.py) into reserved slots.

Output:  assets/readme/hero.png  (2400 x 840, 2x for retina crispness)

If you change copy, layout, or palette, update hero-layout.svg first and then
mirror the change here.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

# ----- paths ----------------------------------------------------------------

HERE = Path(__file__).resolve().parent
ASSETS = HERE.parent.parent
FIG_DIR = ASSETS / "figures" / "wave-propagation"
OUT_PATH = HERE.parent / "hero.png"

PROPAGATION_IMG = FIG_DIR / "propagation-010mm.png"  # 3 panels: ASM | Fresnel | Fraunhofer
MSE_IMG = FIG_DIR / "mse-vs-distance.png"            # MSE vs z evidence

# ----- canvas ----------------------------------------------------------------

# SVG coordinates are 1200 x 440. Render at 2x for crispness on retina.
SVG_W, SVG_H = 1200, 440
SCALE = 2
W, H = SVG_W * SCALE, SVG_H * SCALE

# ----- palette (mirrors hero-layout.svg) ------------------------------------

PAPER = (250, 248, 243)   # #FAF8F3
INK = (14, 17, 22)        # #0E1116
AMBER = (180, 83, 9)      # #B45309
MUTED = (107, 114, 128)   # #6B7280
RULE = (215, 210, 198)    # #D7D2C6
PANEL_BG = (10, 10, 10)   # #0A0A0A
CARD_BG = (255, 255, 255) # white card behind MSE plot

# ----- fonts -----------------------------------------------------------------

# HelveticaNeue.ttc face indices:
#   0 Regular, 1 Bold, 2 Italic, 3 Bold Italic
DISPLAY_REGULAR = "/System/Library/Fonts/HelveticaNeue.ttc"
DISPLAY_BOLD_INDEX = 1
DISPLAY_REGULAR_INDEX = 0
MONO = "/System/Library/Fonts/SFNSMono.ttf"


def font(path: str, size: int, index: int = 0) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(path, size, index=index)


# Tracking (letter-spacing) is applied manually as extra horizontal pixels
# between glyphs.
def draw_tracked(
    draw: ImageDraw.ImageDraw,
    xy: tuple[float, float],
    text: str,
    fill: tuple[int, int, int],
    font_obj: ImageFont.FreeTypeFont,
    tracking: float = 0.0,
) -> None:
    x, y = xy
    cursor = x
    for ch in text:
        draw.text((cursor, y), ch, fill=fill, font=font_obj)
        bbox = font_obj.getbbox(ch)
        cursor += (bbox[2] - bbox[0]) + tracking


# ----- canvas ----------------------------------------------------------------

img = Image.new("RGB", (W, H), PAPER)
draw = ImageDraw.Draw(img)

# Hairlines (only the top one; the bottom hairline would clip the MSE caption)
for y_svg in (40,):
    y = y_svg * SCALE
    draw.line([(48 * SCALE, y), (1152 * SCALE, y)], fill=RULE, width=1 * SCALE)

# ===== LEFT: title block =====================================================

# Eyebrow (mono, tracked uppercase)
draw_tracked(
    draw,
    (48 * SCALE, 72 * SCALE),
    "WAVE OPTICS \u00B7 FIELD NOTES",
    fill=MUTED,
    font_obj=font(MONO, 13 * SCALE),
    tracking=2.2 * SCALE,
)

# Title (display, two lines, Bold)
draw.text(
    (48 * SCALE, 138 * SCALE),
    "Computational",
    fill=INK,
    font=font(DISPLAY_REGULAR, 46 * SCALE, index=DISPLAY_BOLD_INDEX),
)
draw.text(
    (48 * SCALE, 190 * SCALE),
    "Optics Lab",
    fill=INK,
    font=font(DISPLAY_REGULAR, 46 * SCALE, index=DISPLAY_BOLD_INDEX),
)

# Description (four lines, body Regular)
for i, line in enumerate(
    (
        "Runnable Python experiments that translate scalar",
        "diffraction models into inspectable simulations \u2014",
        "with the evidence to know when the output represents",
        "the intended physics.",
    )
):
    draw.text(
        (48 * SCALE, (240 + i * 24) * SCALE),
        line,
        fill=INK,
        font=font(DISPLAY_REGULAR, 18 * SCALE, index=DISPLAY_REGULAR_INDEX),
    )

# Tag chips (mono, amber, tracked)
draw_tracked(
    draw,
    (48 * SCALE, 358 * SCALE),
    "Helmholtz \u00B7 FFT grids \u00B7 quantitative evidence",
    fill=AMBER,
    font_obj=font(MONO, 12 * SCALE),
    tracking=1.4 * SCALE,
)

# Published site link
draw_tracked(
    draw,
    (48 * SCALE, 395 * SCALE),
    "Published: janice143.github.io/computational-optics",
    fill=MUTED,
    font_obj=font(MONO, 12 * SCALE),
    tracking=0.4 * SCALE,
)

# ===== RIGHT: proof scene ====================================================

# Right-side eyebrow
draw_tracked(
    draw,
    (660 * SCALE, 72 * SCALE),
    "PROPAGATION AT z = 10 mm",
    fill=MUTED,
    font_obj=font(MONO, 11 * SCALE),
    tracking=1.8 * SCALE,
)

# ----- Paste the 3-panel propagation image ----------------------------------
# Reserved slot: x=660..1152, y=82..232 (492 wide, 150 high)
slot_x, slot_y, slot_w, slot_h = 660, 82, 492, 150
slot_box_px = (slot_x * SCALE, slot_y * SCALE, (slot_x + slot_w) * SCALE, (slot_y + slot_h) * SCALE)

# Black frame behind the panels (matches the panels' own black bg)
draw.rectangle(slot_box_px, fill=PANEL_BG)

panel_src = Image.open(PROPAGATION_IMG).convert("RGBA")
panel_src_w, panel_src_h = panel_src.size
target_w = slot_w * SCALE
target_h = slot_h * SCALE
fit_scale = min(target_w / panel_src_w, target_h / panel_src_h)
fit_w = int(panel_src_w * fit_scale)
fit_h = int(panel_src_h * fit_scale)
panel_resized = panel_src.resize((fit_w, fit_h), Image.LANCZOS)
paste_x = slot_box_px[0] + (target_w - fit_w) // 2
paste_y = slot_box_px[1] + (target_h - fit_h) // 2
img.paste(panel_resized, (paste_x, paste_y), panel_resized)

# Caption strip below propagation panels
draw_tracked(
    draw,
    (660 * SCALE, 248 * SCALE),
    "ASM \u00B7 FRESNEL \u00B7 FRAUNHOFER",
    fill=MUTED,
    font_obj=font(MONO, 11 * SCALE),
    tracking=1.4 * SCALE,
)

# ----- Paste the MSE evidence curve -----------------------------------------
# Reserved slot: x=660..1152, y=266..410 (492 wide, 144 high)
# White card so the matplotlib-style line plot is readable.
mse_x, mse_y, mse_w, mse_h = 660, 266, 492, 144
mse_box_px = (mse_x * SCALE, mse_y * SCALE, (mse_x + mse_w) * SCALE, (mse_y + mse_h) * SCALE)
draw.rectangle(mse_box_px, fill=CARD_BG)

mse_src = Image.open(MSE_IMG).convert("RGBA")
mse_src_w, mse_src_h = mse_src.size
target_w = mse_w * SCALE
target_h = mse_h * SCALE
fit_scale = min(target_w / mse_src_w, target_h / mse_src_h)
fit_w = int(mse_src_w * fit_scale)
fit_h = int(mse_src_h * fit_scale)
mse_resized = mse_src.resize((fit_w, fit_h), Image.LANCZOS)
paste_x = mse_box_px[0] + (target_w - fit_w) // 2
paste_y = mse_box_px[1] + (target_h - fit_h) // 2
img.paste(mse_resized, (paste_x, paste_y), mse_resized)

# Caption strip below MSE plot
draw_tracked(
    draw,
    (660 * SCALE, 426 * SCALE),
    "MSE vs PROPAGATION DISTANCE z",
    fill=MUTED,
    font_obj=font(MONO, 11 * SCALE),
    tracking=1.4 * SCALE,
)

# ----- save ------------------------------------------------------------------

OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
img.save(OUT_PATH, format="PNG", optimize=True)
print(f"wrote {OUT_PATH} ({OUT_PATH.stat().st_size / 1024:.1f} KB, {W}x{H})")
